
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.DrawingArea Area;
	
	private global::Gtk.Button DrawGraphic;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Функция ln (x+1)");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 20;
		w1.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Area = new global::Gtk.DrawingArea ();
		this.Area.WidthRequest = 520;
		this.Area.HeightRequest = 300;
		this.Area.Name = "Area";
		this.fixed1.Add (this.Area);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Area]));
		w2.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.DrawGraphic = new global::Gtk.Button ();
		this.DrawGraphic.CanFocus = true;
		this.DrawGraphic.Name = "DrawGraphic";
		this.DrawGraphic.UseUnderline = true;
		this.DrawGraphic.Label = global::Mono.Unix.Catalog.GetString ("Нарисовать график");
		this.fixed1.Add (this.DrawGraphic);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.DrawGraphic]));
		w3.X = 396;
		w3.Y = 13;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 535;
		this.DefaultHeight = 382;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Area.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnAreaExposeEvent);
		this.DrawGraphic.Clicked += new global::System.EventHandler (this.OnDrawGraphicClicked);
	}
}
